name: M3O Kotlin clinets and examples
on:
  repository_dispatch:
    types: [build_publish_kotlin]

jobs:
  generate:
    name: Generate M3O kotlin clients and examples
    runs-on: ubuntu-latest
    steps:
      - name: Check m3o-kotlin repo
        uses: actions/checkout@v2
        with:
          path: m3o-kotlin
        
      - name: Check micro/services repo
        uses: actions/checkout@v2
        with:
          repository: 'micro/services'
          path: services

      - name: Generate m3o-kotlin examples
        uses: GWT-M3O-TEST/m3o-generator-action@main
        with:
          target: 'kotlin'
          services_path: services

      - name: Adjust generated things before pushing
        working-directory: services 
        run: |
          # sync the clients to m3o-kotlin/clinets
          rsync -avz clients/kotlin/ ../m3o-kotlin/
          # sync the examples to m3o-kotlin/examples
          # rsync -avz examples/kotlin/ ../m3o-kotlin/examples/
      
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          cwd: m3o-kotlin
          message: Push to M3O-Kotlin repo
          pathspec_error_handling: exitImmediately